#import "settings/mstyle.typ": *
#import algorithmic: algorithm-figure, style-algorithm
#show: style-algorithm

#show: conf.with(
  handout: false,
  subtitle: [Linear Programming],
)

#let bx = $bold(x)$
#let bb = $bold(b)$
#let b0 = $bold(0)$
#let bc = $bold(c)$
#let by = $bold(y)$
#let bw = $bold(w)$
#title-slide()

= Linear Programming

== What is Linear Programming?
#[
  #set align(horizon)
  #set text(size: 0.9em)
  - Linear programming is an optimization model with a linear objective and linear constraints.
  $
    b_1 & <= x_1a_(1,1) + x_2a_(2,1) + ... + x_n a_(n,1) \
    b_2 & <= x_1a_(1,2) + x_2a_(2,2) + ... + x_n a_(n,2) \
        & ... \
    b_m & underbracket(<=, #[can also\ be $=$ or $>=$]) x_1a_(1,m) + x_2a_(2,m) + ... + x_n a_(n,m)
  $
  #v(-15pt)
  #[ #set align(center)
    #text(size: 0.8em, weight: "bold", fill: red)[
      If we see $=$ it must be $=$ for all, if we see $<=$ or $>=$ likewise.
    ]]
  - Variables may be continuous, and every constraint is either an equality or inequality.
  $
    underbracket(#[$x_1,...x_n in ZZ$], #[Integer form]) #text[#h(10pt) or ] underbracket(#[$x_1,...x_n in RR$], #[Linear form])
  $
  #pause
  *Example:*  $b_j$ is the current electricity demand of the $j$-th node; $a_(i,j)x_i$ is the amount of electricity from plant $i$ used at node $j$; and $x_i$ is the total electricity generated by plant $i$.

  *Goal:* Calculate the values of $x_1,...,x_n$ such that all constraints are satisfied. i.e. we meet the electricity demand. \
  Additionally, we would also prefer $sum_(i=1)^n x_i c_i$ to be minimized. *($c_i$ might be the cost of using the $i$-th power plant.)*
]

== IP's and IP's in Matricial form.
// In a matricial form:
// #v(-10pt)
#definition[
  An Integer program is an optimization problem over $bx in ZZ^n$ that can be written in one of the following six forms:
  #table(
    columns: (1fr, 1fr, 1fr),
    stroke: none,
    [$max{ bc^T bx : A bx <= bb }$],
    [$max{ bc^T bx : A bx <= bb, bx >= b0 }$],
    [$max{ bc^T bx : A bx = bb, bx >= b0 }$],

    [$min{ bc^T bx : A bx >= bb }$],
    [$min{ bc^T bx : A bx >= bb, bx >= b0 }$],
    [$min{ bc^T bx : A bx = bb, bx >= b0 }$],
  )
]
#v(-10pt)
#definition[
  A linear program is an optimization problem over $bx in RR^n$ that can be written in one of the following six forms:
  #table(
    columns: (1fr, 1fr, 1fr),
    stroke: none,
    [$max{ bc^T bx : A bx <= bb }$],
    [$max{ bc^T bx : A bx <= bb, bx >= b0 }$],
    [$max{ bc^T bx : A bx = bb, bx >= b0 }$],

    [$min{ bc^T bx : A bx >= bb }$],
    [$min{ bc^T bx : A bx >= bb, bx >= b0 }$],
    [$min{ bc^T bx : A bx = bb, bx >= b0 }$],
  )
  #v(-5pt)
]
#remark[
  #set align(center)
  #set text(weight: "bold", fill: red)
  #v(-15pt)
  LP's $in$ P but IP's $in$ NPH
]


= Examples
== Incidence matrix
The _incidence_ matrix of a graph $G$ is given by
#place(
  top + center,
  dx: -20%,
  dy: 10%,
  figure(
    image("figures/LPi2.png", width: 50%),
  ),
)

#place(
  top + center,
  dx: 20%,
  dy: 50%,
  figure(
    image("figures/LPi3.png", width: 50%),
  ),
)

#let b1 = $bold(1)$

== Maximum Matching
Given $G$ with $n$ vertices and $m$ edges, we seek a vector $bx in {0,1}^m$ s.t.
- $x_e = 1$ when edge $e$ belongs to the matching, and $x_e = 0$ otherwise.
- maximize $sum_(e in E) x_e = max b1^t bx$. #h(1fr) #tr[(We want maximum matching)]


This vector $bx$ is the characteristic vector of a matching in $G$.

*So far the above doesn't define a matching!*
\ *We need to define constraints.*
#pause
- For every vertex $v in V$: $sum_(e in E : v in e) x_e <= 1$.#h(1fr) #tr[(Every vertex can be matched only once)]
// - $x_e in {0,1}$ for all $e in E$. #h(1fr) #tr[(We either choose an edge or we don't)]
#pause
*or by matricial form*
#place(
  top + center,
  dx: 9%,
  dy: 55%,
  figure(
    image("figures/LPi4.png", width: 70%),
  ),
)

#place(
  top + left,
  dx: 5%,
  dy: 75%,
  block(
    stroke: black,
    inset: 10pt,
    radius: 5pt,
    [
      $
        bx in ZZ^n
      $
      #v(-15pt)
      $
        max b1^t bx
      $
    ],
  ),
)


#pagebreak()
For the max-matching problem, we arrive at the following

#table(
  columns: (0.2fr, 1fr, 1fr),
  stroke: none,
  [],
  [
    #block(
      stroke: black,
      inset: 15pt,
      radius: 5pt,
      [
        #set align(center)
        *IP* for maximum matching
        $
          max_(x in ZZ^m){ b1^t bx : M bx <= b1, bx>=b0}
        $
      ],
    )
  ],

  [
    #v(10pt)
    $underbrace(
      #block(stroke: black, inset: 15pt, radius: 5pt, [
        #set align(center)
        *LP* for maximum matching
        $ max_(bx in RR^m){ b1^t bx : M bx <= b1, bx>=b0} $
      ]), #[This called the: \ *Corresponding LP Relaxation*]
    )$
  ],
)
#remark[
  We dont need to bound $bx <= b1$ as if there exists $i$ for which $x_i> 1$.
  Then, there must exist $j in [m]$ for which $M_(j,i) < 1$.
  But, we know that $M$ is the _incidence matrix_ of $G$ so that
  for exactly two indicies $j_1, j_2$ we have $M_(j_1,i)=1$ and  $M_(j_1,i)=1$.
]

== Vertex Cover
Given $G$ with $n$ vertices and $m$ edges, we seek a vector $by in {0,1}^n$ s.t.
- $y_v = 1$ when vertex $v$ belongs to the *vc*, and $y_v = 0$ otherwise.
- minimize $sum_(v in V) y_v = min b1^t by$. #h(1fr) #tr[(We want minimum vertex-cover)]

*Constaints:* $forall e in E: sum_(v in e) y_v >= 1$ #h(1fr) #tr[(Every edge is covered at least once)]


This vector $by$ is the characteristic vector of a vertex cover in $G$.


#pause
*or by matricial form*
#place(
  top + center,
  dx: 12%,
  dy: 55%,
  figure(
    image("figures/LPi5.png", width: 70%),
  ),
)

#place(
  top + left,
  dx: 5%,
  dy: 75%,
  block(
    stroke: black,
    inset: 10pt,
    radius: 5pt,
    [
      $
        by in ZZ^n
      $
      #v(-15pt)
      $
        min b1^t by
      $
    ],
  ),
)


#pagebreak()
#[
  #set align(horizon)
  For the min-vc problem, we arrive at the following
  #v(-30pt)
  #table(
    columns: (0.2fr, 1fr, 1fr),
    stroke: none,
    [],
    [
      #block(
        stroke: black,
        inset: 15pt,
        radius: 5pt,
        [
          #set align(center)
          *IP* for minimum-vc
          $
            min_(by in ZZ^n){ b1^t by : M^t by >= b1, by>=b0}
          $
        ],
      )
    ],

    [
      #v(41pt)
      $underbrace(
        #block(stroke: black, inset: 15pt, radius: 5pt, [
          #set align(center)
          *LP* for minimum-vc
          $ min_(by in RR^n){ b1^t by : M by >= 1, by>=0} $
        ]), #[This called the: \ *Corresponding LP Relaxation*]
      )$
    ],
  )
]

#pause
*What if we wanted vc with minimum weight?* i.e. every vertex $v in V$ has weight $w_v in RR$?
#pause
$
  min_( by in ZZ^n){ underbrace(
      bw^t by,
      sum_(v in V) w_v dot y_v
    ) : M^t by >= b1, by>=b0}
$

== Vertex Cover vs Maximum Matching
#[
  By Konig we know that in bipartite graphs it must hold
  #v(-10pt)
  #table(
    columns: (0.2fr, 1fr, 0.35fr, 1fr),
    stroke: none,
    [],
    [
      #block(
        stroke: black,
        inset: 15pt,
        radius: 5pt,
        [
          #set align(center)
          *IP* for maximum matching
          #v(-10pt)
          $
            max_(bx in ZZ^n){ b1^t bx : M bx <= b1, bx>=b0}
          $
        ],
      )
    ],
    [
      // #h(-50pt)
      #set align(horizon)
      #set text(size: 5em)
      =],
    [
      #block(
        stroke: black,
        inset: 15pt,
        radius: 5pt,
        [
          #set align(center)
          *IP* for minimum-vc
          #v(-10pt)
          $
            min_(by in ZZ^n){ b1^t by : M^t by >= b1, by>=b0}
          $
        ],
      )
    ],
  )
  #pause
  #v(-15pt)
  In fact
  #v(-15pt)
  #table(
    columns: (0.2fr, 1fr, 0.35fr, 1fr),
    stroke: none,
    [],
    [
      #block(
        stroke: black,
        inset: 15pt,
        radius: 5pt,
        [
          #set align(center)
          *LP* for maximum matching
          #v(-10pt)
          $
            max_(bx in RR^n){ b1^t bx : M bx <= b1, bx>=b0}
          $
        ],
      )
    ],
    [
      // #h(-50pt)
      #set align(horizon)
      #set text(size: 5em)
      =],
    [
      #block(
        stroke: black,
        inset: 15pt,
        radius: 5pt,
        [
          #set align(center)
          *LP* for minimum-vc
          #v(-10pt)
          $
            min_(by in RR^n){ b1^t by : M^t by >= b1, by>=b0}
          $
        ],
      )
    ],
  )
  #pause
  #v(-10pt)
  If $G$ is not bipartite, then in fact
  #place(
    dx: 3%,
    dy: 5%,
    table(
      columns: (0.05fr, 1fr, 0.25fr, 1fr, 0.4fr),
      align: (center, right, left, right, left),
      stroke: none,
      [],
      [
        #block(
          stroke: black,
          inset: 15pt,
          radius: 5pt,
          [
            #set align(center)
            *IP* for maximum matching
            #v(-10pt)
            $
              max_(bx in ZZ^n){ b1^t bx : M bx <= b1, bx>=b0}
            $
          ],
        )
      ],
      [
        // #h(-50pt)
        #set align(horizon)
        #set text(size: 2em)
        $in$ P],
      [
        #block(
          stroke: black,
          inset: 15pt,
          radius: 5pt,
          [
            #set align(center)
            *IP* for minimum-vc
            #v(-10pt)
            $
              min_(by in ZZ^n){ b1^t by : M^t by >= b1, by>=b0}
            $
          ],
        )
      ],
      [
        // #h(-50pt)
        #set align(horizon)
        #set text(size: 2em)
        $in$ NPC],
    ),
  )
]

= Geometric analysis of LP's
== Geometric analysis of LP's
#[
  #set align(horizon)
  Consider the following *LP*:
  #block(width: 30%, stroke: black, radius: 15pt, inset: 15pt)[
    $max x_1+x_2$ \
    $s.b.t.$
    #v(-10pt)
    $
      #h(50pt)-x_1 + x_2 & <=1 \
              x_1 + 6x_2 & <=15 \
              4x_1 - x_2 & <=10 \
       x_1 >= 0 #h(20pt) \
       x_2 >= 0 #h(20pt)
    $
  ]

  #place(
    horizon + center,
    dx: 25%,
    dy: -15%,
    figure(
      image("figures/LPi1.png", width: 52%),
    ),
  )

  #[
    #set align(center)
    #block(stroke: black, radius: 15pt, inset: 15pt)[
      $
        max_(x in RR^2) (1, 1) dot (x_1, x_2)
        text("s.t.") quad
        mat(
          -1, 1;
          4, 6;
          4, -1
        )
        mat(
          x_1;
          x_2
        )
        <=
        mat(
          1;
          15;
          10
        ), quad
        (x_1, x_2) >= (0, 0)
      $
    ]
  ]
]

#pagebreak()
#v(80pt)
#block(width: 50%)[
  Solving the problem Geometrically,
  would mean taking the line $x_1+x_2=c$
  and moving it in the direction $(1,1)$ until we get out of constraint.
]
#place(
  horizon + center,
  dx: 25%,
  dy: -15%,
  figure(
    image("figures/LPi6.png", width: 52%),
  ),
)

#pause
#place(
  horizon + center,
  dx: -25%,
  dy: 30%,
  figure(
    image("figures/LPi7.png", width: 46%),
  ),
)
#place(
  horizon + center,
  dx: 25%,
  dy: 34%,
  block(width: 50%)[
    #set align(center)
    If we change the constraint to $max 1/6x_1 + x_2$. \
    Then, we have infinitely maxny solutions.
  ],
)
#place(
  horizon + center,
  dx: -2%,
  dy: 34%,
  block(width: 50%)[
    #set text(size: 2em)
    #set align(center)
    $<==$
  ],
)


== Standard forms of LP's
#set align(horizon)
#definition[
  A Linear program in a one of the following 2-forms:
  #table(
    columns: (0.3fr, 1fr, 1fr),
    stroke: none,
    [], [$max{ bc^T bx : A bx = bb, bx >= b0 }$], [$min{ bc^T bx : A bx = bb, bx >= b0 }$],
  )
  is said to be in *equational form*;
]
#remark[
  Optimal solution for *LP's* in *equational form* are the easiest to exaplain and we will focus on those.
]

// == Example: a small LP
// #set align(horizon)
// #columns(2, [
//   - Maximize $z = 3x_1 + 2x_2$
//   - subject to:
//     - $x_1 + x_2 <= 4$
//     - $x_1 <= 2$
//     - $x_2 <= 3$
//     - $x_1, x_2 >= 0$
//   - The feasible set is a convex polygon.
//   - The optimal solution occurs at a vertex.
//   #colbreak()
//   #cetz.canvas({
//     import cetz.draw: *
//     line((0, 0), (4, 0), (4, 3), (0, 3), close: true, fill: rgb("#a0c8f0"), stroke: none)
//     line((0, 0), (4, 0), stroke: 1pt + gray)
//     line((0, 0), (0, 3), stroke: 1pt + gray)
//     line((0, 4), (4, 0), stroke: (paint: blue, thickness: 2pt))
//     line((2, 0), (2, 3), stroke: (paint: blue, thickness: 2pt))
//     line((0, 3), (4.5, 3), stroke: (paint: blue, thickness: 2pt))
//     circle((2, 3), radius: 0.12, fill: black, stroke: none)
//     content((2, 3.3), [$(2,3)$], anchor: "south")
//   })
// ])
// #pause

// == Feasible Region
// - The feasible region of an LP is the intersection of half-spaces.
// - It is a convex polyhedron in high dimensions.
// - If an optimal solution exists, some extreme point is optimal.
// #pause
// #remark[
//   For two variables, each inequality defines a half-plane and the feasible region is a polygon.
// ]

// == Standard Form
// #definition[
//   A linear program in standard form is:
//   $
//     max{ c^T x : A x = b, x >= 0 }.
//   $
// ]
// - Every LP can be converted to standard form using slack and surplus variables.
// #pause
// - Example: $x_1 + x_2 <= 4$ becomes $x_1 + x_2 + s = 4$ with $s >= 0$.

// == Basic Feasible Solutions
// - A basic feasible solution is obtained by selecting a basis of $n$ independent constraints.
// - Set the non-basic variables to $0$ and solve the remaining equations.
// - If the solution is feasible, it corresponds to an extreme point.
// #pause
// #theorem[
//   If an LP has an optimal solution, then there is an optimal basic feasible solution.
// ]

// == The Simplex Method
// - Start from an initial basic feasible solution.
// - Move along edges of the feasible polyhedron to improve the objective.
// - Stop when no entering variable can improve the objective.
// #algorithm-figure(
//   "",
//   vstroke: .5pt + luma(200),
//   {
//     import algorithmic: *
//     Procedure("simplex", "LP", {
//       Assign([$B$], [_initial_ basis])
//       Assign([$x$], [_basic_ feasible solution])
//       While([there is an entering variable], {
//         Line([Choose entering variable $j$])
//         Line([Choose leaving variable $i$])
//         Line([Update basis $B$ and solution $x$])
//       })
//       LineBreak
//       Return([$x$])
//     })
//   },
// )

// == Duality
// - Every primal LP has a dual LP.
// - For primal $
//     max{ c^T x : A x <= b, x >= 0}
//   $ the dual is
//   $
//     min{ b^T y : A^T y >= c, y >= 0}
//   $.
// #pause
// - Weak duality: any feasible primal $x$ and dual $y$ satisfy $c^T x <= b^T y$.
// - Strong duality: if either problem has an optimal solution, both do and the objective values coincide.

// == Primal and Dual Example
// #grid(
//   columns: (1fr, 1fr),
//   stroke: none,
//   [
//     #text[
//       Primal:
//       $max 3x_1 + 2x_2$
//       s.t. $x_1 + x_2 <= 4$
//       $x_1 <= 2$
//       $x_2 <= 3$
//       $x_1, x_2 >= 0$
//     ]
//     #text[
//       Dual:
//       $min 4y_1 + 2y_2 + 3y_3$
//       s.t. $y_1 + y_2 >= 3$
//       $y_1 + y_3 >= 2$
//       $y_1, y_2, y_3 >= 0$
//     ]
//   ]
// )

// == Applications
// - Production planning and resource allocation.
// - Transportation and assignment problems.
// - Network flows and matching.
// - Machine learning models such as support vector machines.
// #pause
// - Linear programming is a foundational optimization tool in algorithms and operations research.

// == Summary
// - A linear program optimizes a linear objective subject to linear constraints.
// - The feasible region is convex and optimal solutions lie at vertices.
// - The simplex method moves between basic feasible solutions.
// - Duality provides certificates of optimality and bounds.

